Repository CMU-17313Q/nodebb-f24-syntax_squad, pull requests merged in 2024-10, with the labels that each got.

#67 Completed anonymous backend testing
  test/posts.js
Labels: User story 1, Back-end, Sprint 2, Testing

#68 Emoji feature front end
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  node_modules/nodebb-theme-harmony/templates/partials/topic/emoji-dropdown.tpl
  node_modules/nodebb-theme-harmony/templates/partials/topic/post.tpl
  node_modules/nodebb-theme-harmony/templates/partials/topic/topic-menu-list.tpl
  node_modules/nodebb-theme-harmony/templates/topic.tpl
  src/topics/data.js
  test/topics.js
Labels: enhancement, User story 9, Front-end, Sprint 2

#69 Revert "Completed anonymous backend testing"
  test/posts.js
Labels: bug, User story 1, Back-end, Sprint 2, Testing

#66 Adding backend testing for search function
  src/topics/data.js
  src/topics/search.js
  test/topics.js
Labels: User story 3, Back-end, Sprint 2, Testing

#64 Adding front-end back-end connection for search
  node_modules/nodebb-theme-harmony/templates/topic.tpl
  public/openapi/read.yaml
  public/openapi/read/topics.yaml
  public/src/client/topic.js
  public/src/client/topic/posts.js
  public/src/client/users.js
  src/api/topics.js
  src/api/users.js
  src/controllers/topics.js
  src/controllers/users.js
  src/routes/api.js
  src/topics/posts.js
  src/topics/search.js
  src/user/search.js
  test/api.js
Labels: User story 3, Sprint 2, Connection, API routing

#71 Automating testing for anonymous feature
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  node_modules/nodebb-theme-harmony/templates/partials/topic/emoji-dropdown.tpl
  node_modules/nodebb-theme-harmony/templates/partials/topic/post.tpl
  node_modules/nodebb-theme-harmony/templates/topic.tpl
  test/posts.js
Labels: User story 1, Back-end, Sprint 2, Testing

#74 Completed steps for azure app deployment
  .github/workflows/azure-deploy-f24.yml
Labels: Back-end

#84 Re-adding front-end changes
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  node_modules/nodebb-theme-harmony/templates/partials/topic/emoji-dropdown.tpl
  node_modules/nodebb-theme-harmony/templates/partials/topic/post.tpl
  node_modules/nodebb-theme-harmony/templates/topic.tpl
Labels: Front-end, Restoration
